# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-30 16:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sendletters', '0002_auto_20160129_1609'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriptionsignup',
            options={'verbose_name': 'подписка на рассылку', 'verbose_name_plural': 'подписки на рассылку'},
        ),
    ]
