# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-26 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advert',
            options={'verbose_name': 'объявление', 'verbose_name_plural': 'объявления'},
        ),
        migrations.AddField(
            model_name='advert',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='дата публикации'),
        ),
    ]
