# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-26 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0002_auto_20160126_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='distance',
            field=models.BooleanField(default=False, verbose_name='удаленно'),
        ),
    ]
