# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-26 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0003_auto_20160126_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='advert',
            name='city',
            field=models.CharField(max_length=120, null=True, verbose_name='город'),
        ),
    ]
