# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-02 08:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0005_auto_20160130_0739'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advert',
            old_name='distance',
            new_name='is_remote',
        ),
    ]
