# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-10 14:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adverts', '0006_auto_20160202_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='advert',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='автор вакансии'),
        ),
    ]
