# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-02 08:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_useractivationkey'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='recruiter',
            new_name='is_recruiter',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='worker',
            new_name='is_worker',
        ),
    ]
