# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-05 15:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20160202_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractivationkey',
            name='password_recovery_token',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
