# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-06 07:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_useractivationkey_password_recovery_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useractivationkey',
            name='password_recovery_token',
        ),
    ]
