# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-20 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20160220_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_to_contact',
            field=models.EmailField(blank=True, default='', help_text='может отличаться от указанной при регистрации', max_length=120, null=True, verbose_name='электропочта для связи'),
        ),
        migrations.AddField(
            model_name='user',
            name='homepage',
            field=models.URLField(blank=True, default='', null=True, verbose_name='персональный сайт'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_recruiter',
            field=models.BooleanField(default=False, verbose_name='ищу работников'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_worker',
            field=models.BooleanField(default=False, verbose_name='ищу работу'),
        ),
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.CharField(blank=True, default='', max_length=120, null=True, verbose_name='город'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=120, null=True, verbose_name='номер телефона'),
        ),
    ]
