# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-20 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20160220_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='slug',
            field=models.SlugField(default=None, unique=True),
        ),
    ]
