# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-20 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_user_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='slug',
            field=models.SlugField(default=None, null=True, unique=True),
        ),
    ]
