# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-20 10:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email_to_contact',
            field=models.EmailField(default=None, max_length=120, verbose_name='электропочта'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='homepage',
            field=models.URLField(default=None, verbose_name='персональный сайт'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_recruiter',
            field=models.BooleanField(default=False, verbose_name='ищу работников'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_worker',
            field=models.BooleanField(default=False, verbose_name='ищу работу'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, default=None, max_length=120, verbose_name='номер телефона'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='location',
            field=models.CharField(blank=True, default=None, max_length=120, null=True),
        ),
    ]
