# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-20 11:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20160220_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='email_to_contact',
            field=models.EmailField(default=None, help_text='может отличаться от указанной при регистрации', max_length=120, verbose_name='электропочта для связи'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='homepage',
            field=models.URLField(blank=True, default=None, null=True, verbose_name='персональный сайт'),
        ),
    ]
