# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-20 12:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20160220_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, default=None, max_length=120, null=True, verbose_name='номер телефона'),
        ),
    ]
