# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-20 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20160220_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='email_to_contact',
            field=models.EmailField(blank=True, default='', help_text='может отличаться от указанной при регистрации', max_length=120, null=True, verbose_name='электропочта для связи'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='homepage',
            field=models.URLField(blank=True, default='', null=True, verbose_name='персональный сайт'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='location',
            field=models.CharField(blank=True, default='', max_length=120, null=True, verbose_name='город'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=120, null=True, verbose_name='номер телефона'),
        ),
    ]
