# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-20 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_auto_20160220_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='slug',
            field=models.SlugField(default='', max_length=120),
        ),
    ]
